# Here you can specify default options for TinyMCE across all controllers
#
plugins:
  - image imagetools
  - link
  - emoticons
  - code
  - charmap
  - textcolor colorpicker
  - print
  - lists
  - advlist
  - insertdatetime
  - directionality
  - media
  - preview
toolbar:
  - fontsizeselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent | forecolor backcolor | emoticons charmap | subscript superscript | insertdatetime
  - undo redo removeformat | print | link | media | preview | code |